### ISSUE TITLE
Fehlermeldung bei Einbindung von JavaFX

### ISSUE THREAD

**Issue by TubaKarte** [herrhundt/BonjourGUI#10]
![IMG_20200521_130644_787](https://user-images.githubusercontent.com/43959198/82599962-71da4980-9bad-11ea-91be-76d492f8de34.jpg)

Hallo Leute,
Ich bekomme immer diesen Fehler, obwohl ich genau das befolgt habe, was uns im Video gezeigt wurde. Würde mich über Hifle freuen.

**Comment by herrhundt** [comment]
Es ist merkwürdig, dass die Datei swt **(1)** .jar heißt. Hier liegt vermutlich das Problem, ggf ist das beim Download oder Entpacken passiert. 
Hilfreich wären zudem mehr Angaben, z.B. Screenshots von deinen Run-Configs.

**Comment by TubaKarte** [comment]
Ähm, ich habe gerade IntelliJ gestartet und wollte mir den Fehler nochmal anschauen und jetzt ist er nicht mehr da. Keine Ahnung woran es also lag, vielleicht wurde irgendwas gestern falsch hinterlegt oder so und ne Änderung nicht richtig übernommen, die erst durch nen Neustart des PCs übernommen wurde...
