### ISSUE TITLE
JavaFX Bibliothek fehlt

### ISSUE THREAD

**Issue by MrDyro** [herrhundt/BonjourGUI#5]
Nach dem herunterladen kann ich das Programm nicht starten, da die Abhängigkeit zu JavaFX fehlt.

**Comment by herrhundt** [comment]
Ich verwende das SDK von Zulu, siehe: [https://www.azul.com/downloads/zulu/zulufx/](url)

**Comment by herrhundt** [comment]
Habe es gerade einmal mit dem JDK 13 (OpenJDK) und externem JavaFX-SDK versucht, hier findet er die JavaFX-Bibliotheken aber auch nicht, obwohl ich die Schritte aus [https://www.jetbrains.com/help/idea/javafx.html](url) beachtet habe.

**Comment by MrDyro** [comment]
Kann man die JavaFX Abhänigkeit als .jar ins Projekt ziehen?

**Comment by herrhundt** [comment]
> Habe es gerade einmal mit dem JDK 13 (OpenJDK) und externem JavaFX-SDK versucht, hier findet er die JavaFX-Bibliotheken aber auch nicht, obwohl ich die Schritte aus [https://www.jetbrains.com/help/idea/javafx.html](url) beachtet habe.

Hierzu habe ich nun eine Lösung gefunden, 
![run_configuration](https://user-images.githubusercontent.com/59929867/81506191-e92df480-92f4-11ea-9205-0ba54c7751a5.png)

Bei der Konfiguration muss man den Pfad der JavaFX-SDK/lib korrekt einbinden, bei mir gab es wegen des Leerzeichens im Pfad ein Problem, setzt man das ganze in Anführungszeichen, wird der Pfad korrekt erkannt. 
Zudem hab ich alle .jar aus dem /lib-Ordner ins Projekt gezogen.

**Comment by herrhundt** [comment]
> Kann man die JavaFX Abhänigkeit als .jar ins Projekt ziehen?
Das dürfte nicht funktioniere, siehe hier: 
[https://github.com/javafxports/openjdk-jfx/issues/236#issuecomment-426583174](url)

**Comment by herrhundt** [comment]
> Kann man die JavaFX Abhänigkeit als .jar ins Projekt ziehen?

Das dürfte so nicht funktionieren, siehe hier: 
https://github.com/javafxports/openjdk-jfx/issues/236#issuecomment-426583174

**Comment by herrhundt** [comment]
> > Kann man die JavaFX Abhänigkeit als .jar ins Projekt ziehen?
> 
> Das dürfte so nicht funktionieren, siehe hier:
> [javafxports/openjdk-jfx#236 (comment)](https://github.com/javafxports/openjdk-jfx/issues/236#issuecomment-426583174)

Auf dem verlinkten Issue ist zwar ein Workaround beschrieben, aber so richtig "knorke" sieht der auch nicht aus. Läuft das Programm mittlerweile
